import { Profile, Match, User } from "@/types";

export const CURRENT_USER: User = {
  id: "me",
  name: "Mohd Zaid",
  username: "mohdzaid",
  initials: "MZ",
  age: 24,
  city: "Delhi",
  job: "Software Engineer",
  bio: "Building the future one line at a time ✨",
  gender: "Man",
  lookingFor: "Long-term relationship",
  profileViews: 142,
  likesReceived: 8,
  matchesCount: 4,
};

export const PROFILES: Profile[] = [
  {
    id: "laila",
    name: "Laila",
    age: 23,
    tagline: '"I am not here for hookups"',
    emoji: "🧘",
    gender: "Woman",
    orientation: "Straight",
    location: "Sector 2, Noida",
    height: "5'4",
    drinks: "No",
    exercise: "Yes",
    marijuana: "No",
    pets: "Cat",
    children: "Don't Want",
    job: "Chartered Accountant",
    education: "University of Delhi",
    religion: "Hindu",
    city: "Noida",
    languages: "English, Hindi",
    intent: "Long-term relationship",
    photos: ["🧘", "🌿", "🪷"],
    quotes: [
      "Yoga: The journey of the self, through the self, to the self.",
      "Breathe in peace, breathe out stress.",
      "Yoga is the art of waking up.",
    ],
  },
  {
    id: "priya",
    name: "Priya",
    age: 25,
    tagline: '"Art is how I tell my story"',
    emoji: "🎨",
    gender: "Woman",
    orientation: "Straight",
    location: "Hauz Khas, Delhi",
    height: "5'5",
    drinks: "Yes",
    exercise: "Yes",
    marijuana: "No",
    pets: "Dog",
    children: "Open",
    job: "UX Designer",
    education: "NID Ahmedabad",
    religion: "Hindu",
    city: "Delhi",
    languages: "English, Hindi",
    intent: "Long-term relationship",
    photos: ["🎨", "🖌️", "🌺"],
    quotes: [
      "Design is thinking made visual.",
      "Colors speak louder than words.",
      "Every canvas tells a story.",
    ],
  },
  {
    id: "sarah",
    name: "Sarah",
    age: 27,
    tagline: '"Music is my first language"',
    emoji: "🎵",
    gender: "Woman",
    orientation: "Straight",
    location: "Bandra, Mumbai",
    height: "5'6",
    drinks: "Yes",
    exercise: "No",
    marijuana: "No",
    pets: "None",
    children: "Want",
    job: "Music Producer",
    education: "Berklee Online",
    religion: "Christian",
    city: "Mumbai",
    languages: "English, Marathi",
    intent: "Serious relationship",
    photos: ["🎵", "🎹", "🎤"],
    quotes: [
      "Life without music is unimaginable.",
      "Every beat tells a story.",
      "Harmony is the key to everything.",
    ],
  },
  {
    id: "nadia",
    name: "Nadia",
    age: 26,
    tagline: '"Books and chai are life"',
    emoji: "📚",
    gender: "Woman",
    orientation: "Straight",
    location: "Indiranagar, Bengaluru",
    height: "5'3",
    drinks: "No",
    exercise: "Yes",
    marijuana: "No",
    pets: "Cat",
    children: "Don't Want",
    job: "Content Writer",
    education: "Jadavpur University",
    religion: "Muslim",
    city: "Bengaluru",
    languages: "English, Bengali",
    intent: "Casual dating",
    photos: ["📚", "☕", "🌸"],
    quotes: [
      "A reader lives a thousand lives.",
      "Chai solves everything.",
      "Words have the power to change worlds.",
    ],
  },
  {
    id: "meera",
    name: "Meera",
    age: 24,
    tagline: '"Wanderlust with a side of biryani"',
    emoji: "🌍",
    gender: "Woman",
    orientation: "Straight",
    location: "Jubilee Hills, Hyderabad",
    height: "5'2",
    drinks: "No",
    exercise: "Yes",
    marijuana: "No",
    pets: "None",
    children: "Open",
    job: "Travel Blogger",
    education: "BITS Hyderabad",
    religion: "Hindu",
    city: "Hyderabad",
    languages: "English, Telugu",
    intent: "Long-term relationship",
    photos: ["🌍", "🍛", "🏔️"],
    quotes: [
      "Not all those who wander are lost.",
      "Food is the language of love.",
      "Every city has a story to tell.",
    ],
  },
  {
    id: "riya",
    name: "Riya",
    age: 22,
    tagline: '"Coding by day, stargazing by night"',
    emoji: "💻",
    gender: "Woman",
    orientation: "Straight",
    location: "Koramangala, Bengaluru",
    height: "5'4",
    drinks: "No",
    exercise: "Yes",
    marijuana: "No",
    pets: "Dog",
    children: "Open",
    job: "Software Engineer",
    education: "IIT Bombay",
    religion: "Hindu",
    city: "Bengaluru",
    languages: "English, Hindi",
    intent: "Long-term relationship",
    photos: ["💻", "🌌", "🐕"],
    quotes: [
      "The best code is no code at all.",
      "Stars are just distant suns waiting to be explored.",
      "Debug your life like you debug your code.",
    ],
  },
];

export const INITIAL_MATCHES: Match[] = [
  {
    id: "match-laila",
    profile: PROFILES[0],
    messages: [
      { id: "1", senderId: "laila", text: "Hi! I saw you liked yoga too 🧘‍♀️", timestamp: new Date(Date.now() - 600000) },
      { id: "2", senderId: "me", text: "Yes! I just started recently. How long have you been practicing?", timestamp: new Date(Date.now() - 540000) },
      { id: "3", senderId: "laila", text: "About 3 years now! It completely changed how I handle stress 😌", timestamp: new Date(Date.now() - 480000) },
      { id: "4", senderId: "laila", text: "haha yes yoga is literally my whole personality 😂", timestamp: new Date(Date.now() - 120000) },
    ],
    lastMessage: "haha yes yoga is literally my whole personality 😂",
    lastMessageTime: new Date(Date.now() - 120000),
    unreadCount: 2,
    isOnline: true,
  },
  {
    id: "match-priya",
    profile: PROFILES[1],
    messages: [
      { id: "1", senderId: "priya", text: "Hey! Love your vibe 🎨", timestamp: new Date(Date.now() - 3600000) },
      { id: "2", senderId: "me", text: "That art exhibit sounds amazing, would love to go!", timestamp: new Date(Date.now() - 3000000) },
    ],
    lastMessage: "That art exhibit sounds amazing, would love to go!",
    lastMessageTime: new Date(Date.now() - 3600000),
    unreadCount: 0,
    isOnline: false,
  },
  {
    id: "match-sarah",
    profile: PROFILES[2],
    messages: [
      { id: "1", senderId: "me", text: "What's your favorite genre?", timestamp: new Date(Date.now() - 10800000) },
    ],
    lastMessage: "You: What's your favorite genre?",
    lastMessageTime: new Date(Date.now() - 10800000),
    unreadCount: 0,
    isOnline: true,
  },
];

export const AUTO_REPLIES = [
  "That's so interesting! 😊",
  "haha yes totally 😂",
  "Aww that's so sweet! 💕",
  "Tell me more! 👀",
  "We definitely need to plan something ✨",
  "You seem really fun to talk to 😄",
  "I was literally just thinking about that!",
  "Okay now I'm intrigued 🤔",
  "No way, same here! 🙌",
  "That made me smile 😊",
];
